---
- name: Provision and configure servers
  hosts: webservers
  become: true
  vars_files:
    - roles/mysql/vars/vault.yml

  roles:
    - common 
    - user
    - nginx
    - mysql
    - php
    - deploy_app

#note: The vault.yml file contain the variable 'vault_db_password' 