- name: Install PHP and necessary extensions
  apt:
    name: 
      - php-fpm
      - php-mysql
      - php-cli
      - php-curl
      - php-xml
      - php-mbstring
      - unzip
    state: present
    update_cache: yes

- name: Running PHP-FPM
  service:
    name: php7.4-fpm
    state: started
    enabled: yes
